// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// GET_VIDEO
export const GET_VIDEO_REQUEST = 'GET_VIDEO_REQUEST';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAILED = 'GET_VIDEO_FAILED';

// SHARE_VIDEO
export const SHARE_VIDEO_REQUEST = 'SHARE_VIDEO_REQUEST';
export const SHARE_VIDEO_SUCCESS = 'SHARE_VIDEO_SUCCESS';
export const SHARE_VIDEO_FAILED = 'SHARE_VIDEO_FAILED';
