// GET ERRORS
export const GET_ERRORS = 'GET_ERRORS';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// GET_POSTS
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

// SHARE_VIDEO
export const SHARE_VIDEO_REQUEST = 'SHARE_VIDEO_REQUEST';
export const SHARE_VIDEO_SUCCESS = 'SHARE_VIDEO_SUCCESS';

// FATEVORITES
export const FATEVORITES_REQUEST = 'FATEVORITES_REQUEST';
export const FATEVORITES_SUCCESS = 'FATEVORITES_SUCCESS';

// GET_MY_INFO
export const GET_MY_INFO_REQUEST = 'GET_MY_INFO_REQUEST';
export const GET_MY_INFO_SUCCESS = 'GET_MY_INFO_SUCCESS';

// GET_POST_DETAIL
export const GET_POST_DETAIL_REQUEST = 'GET_POST_DETAIL_REQUEST';
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
